SELECT t1.TITLE, t1.BOARD_ID, t2.REPLY_ID, t2.WRITER_ID, t2.CONTENTS, DATE_FORMAT(t2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_BOARD AS t1
JOIN USED_GOODS_REPLY AS t2
ON t1.BOARD_ID = t2.BOARD_ID
WHERE t1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY t2.CREATED_DATE ASC, t1.TITLE ASC